FROM codingcorp-docker.pkg.coding.net/registry/release/spin-base:1.0

MAINTAINER delivery-engineering@netflix.com
COPY --from=orca-compile /compiled_sources/orca-web/build/install/orca /opt/orca
COPY --from=orca-compile /compiled_sources/coding-deploy/config /opt/spinnaker/config
COPY --from=orca-compile /compiled_sources/coding-deploy/scripts /opt/spinnaker/scripts

RUN adduser -D -S spinnaker
USER spinnaker

ENTRYPOINT ["/sbin/tini", "--", "/opt/orca/bin/orca"]
